#!/bin/sh

config_dir=/etc/egpu-switcher
config_file=${config_dir}/egpu-switcher.conf

# remove the config file + dir on purge
if [ ${1} = "purge" ] && [ -e ${config_dir} ]; then
    rm -f ${config_file}
    rm -fd ${config_dir}
fi