name: CI
on:
  pull_request:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go: [ '1.19' ]
    uses: ./.github/workflows/go-test.yml
    with:
      go-version: ${{ matrix.go }}

