# reusable workflow
name: Test

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests (Go ${{ inputs.go-version }})
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}
          cache: true

      - name: Run tests
        run: make test

  lint:
    runs-on: ubuntu-latest
    name: Run linters (Go ${{ inputs.go-version }})
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}
          cache: true

      - name: Run linters
        run: make lint

