name: TEST WORKFLOW

on:
  push:
    branches:
      - 'dev'

jobs:
  test:
    strategy:
      matrix:
        go: [ '1.19' ]
    uses: ./.github/workflows/go-test.yml
    with:
      go-version: ${{ matrix.go }}

  build:
    needs: test
    strategy:
      matrix:
        go: [ '1.19' ]
        arch: [ 'amd64', 'arm64' ]
    uses: ./.github/workflows/go-build.yml
    with:
      go-version: ${{ matrix.go }}
      go-arch: ${{ matrix.arch }}
      filename: egpu-switcher

  # package-arch:
  #   needs: build

  # package-deb:
  #   needs: build

  # create-release:
  #   needs: [package-arch, package-deb]
