name: TEST WORKFLOW

on:
  push:
    branches:
      - 'dev'

jobs:
  test:
    # name: Run tests and linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.19' ]
    steps:
      - uses: ./.github/workflows/test.yml
        with:
          go-version: ${{ matrix.go }}
