name: TEST WORKFLOW

on:
  push:
    branches:
      - 'dev'

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go: [ '1.19' ]
    uses: ./.github/workflows/go-test.yml
    with:
      go-version: ${{ matrix.go }}

  build:
    name: Build
    needs: test
    strategy:
      matrix:
        go: [ '1.19' ]
        arch: [ 'amd64', 'arm64' ]
    uses: ./.github/workflows/go-build.yml
    with:
      go-version: ${{ matrix.go }}
      go-arch: ${{ matrix.arch }}
      filename: egpu-switcher

  # TODO: Create Github Release

  # TODO: AUR Publish
  aur:
    name: Publish to AUR
    needs: [test, build]
    uses: ./.github/workflows/aur-release.yml
    with:
      version: ${{ github.ref }}

  # TODO: Debian package
  # package-deb:
  #   needs: build

