name: TEST WORKFLOW

on:
  push:
    branches:
      - 'dev'

jobs:
  test:
    strategy:
      matrix:
        go: [ '1.19' ]
    uses: ./.github/workflows/test.yml
    with:
      go-version: ${{ matrix.go }}

